# Generated by Django 5.2.4 on 2025-08-31 13:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_imgs_placeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Длинное описание'),
        ),
    ]
