# Generated by Django 5.2.5 on 2025-09-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20250902_1858'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='placeimage',
            new_name='places_plac_order_66e296_idx',
            old_name='places_order_idx',
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates',
            field=models.JSONField(verbose_name='Координаты'),
        ),
    ]
